[package]
name = "jdoit"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
skim = "3.5.0"
toml = { version = "1.0.3", features = ["serde"] }
